source("util.R")
# remotes::install_github("kjhealy/covdata")
# library(covdata)
# metro_fips <- get_metro_census()
# save(metro_fips, file = "./data/metro.RDA")
load("./data/metro.RDA")
ts_us <- get_metro_ts(metro_fips)
save(ts_us, file = "./data/ts.RDA") 
